### ISSUE TITLE
segfault in sp_destroy(env)

### ISSUE THREAD

**Issue by shadeware** [pmwkaa/sophia#117]
Slightly modified example from documentation:
```
// SP is helper macro that throws exception in case of error

int
main(int argc, char** argv)
{
  if (argc != 2)
    {
      std::cerr << "usage: " << *argv << " table_count" << std::endl;
      return EXIT_FAILURE;
    }

  auto table_count = std::stoi(argv[1]);

  void* env = sp_env();
  SP(env);
  SP(sp_setstring(env, "sophia.path", "./storage", 0));
  SP(sp_open(env));

  auto sp_version = (char*)SP(sp_getstring(env, "sophia.version", nullptr));
  std::cout << "sophia.version = " << sp_version << std::endl;
  free(sp_version);

  for (int i = 0; i < table_count; ++i)
    {
      char table_name[30];
      auto c = sprintf(table_name, "db.t_%d", i + 1);
      assert(c > 0);
      SP(sp_setstring(env, "db", table_name + 3, 0));
      void* db = SP(sp_getobject(env, table_name));
      SP(sp_open(db));
      SP(sp_destroy(db));
    }

  std::cout << "destroing env..." << std::endl;
  sp_destroy(env);
  std::cout << "Done." << std::endl;
}
```
Full code - https://gist.github.com/shadeware/46670ed7523ace3f7da0
```
$ rm -rf ./storage && ./a.out 10 && echo $? #ok even with valgrind
sophia.version = 2.1.1
destroing env...
Done.
0
$ rm -rf ./storage && ./a.out 20 && echo $?
sophia.version = 2.1.1
destroing env...
Segmentation fault (core dumped)
```
Backtrace from gdb:
```
#0  0x00007ffff7066892 in __GI___libc_free (mem=0x624000) at malloc.c:2949
#1  0x00007ffff7b84889 in ss_stdafree (a=0x6174c8, ptr=0x624000) at sophia/std/ss_stda.c:35
#2  0x00007ffff7b672d2 in ss_free (a=0x6174c8, ptr=0x624000) at sophia/std/ss_a.h:56
#3  0x00007ffff7b982ed in sl_poolshutdown (p=0x617840) at sophia/log/sl.c:237
#4  0x00007ffff7bb1249 in se_destroy (o=0x616c20) at sophia/environment/se.c:136
#5  0x00007ffff7bc222d in sp_destroy (ptr=0x616c20) at sophia/sophia/sophia.c:104
#6  0x000000000040258d in main ()
```
```
$ rm -rf ./storage &&  ./a.out 30
sophia.version = 2.1.1
terminate called after throwing an instance of 'std::logic_error'
  what():  sphia error in 'test.cpp":87: sp_open(db)', reason = 'sophia/index/si_recover.c:158 directory '��,�/t_25' create error: No such file or directory'
Aborted (core dumped)
```
Looks like buffer with sophia.path is damaged.
sophia-test is successful.

**Comment by pmwkaa** [comment]
thanks a lot
